# More option see https://github.com/DreamMaoMao/mango/wiki/
source=~/.config/mango/configurations/envs.conf
source=~/.config/mango/configurations/keybinds.conf
source=~/.config/mango/configurations/tagrules.conf
source=~/.config/mango/configurations/mousebinds.conf
source=~/.config/mango/configurations/animations.conf
source=~/.config/mango/configurations/trackpad.conf
source=~/.config/mango/configurations/wineffects.conf
source=~/.config/mango/configurations/scoller.conf
source=~/.config/mango/configurations/master_stack.conf
source=~/.config/mango/configurations/misc.conf
source=~/.config/mango/configurations/appearance.conf
source=~/.config/mango/configurations/overview.conf
source=~/.config/mango/configurations/layerrules.conf

